language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - stable

before_install:
  - curl https://stainless-steel.github.io/travis/install_gfortran.sh | bash

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran

notifications:
  email: false
