language: rust

dist: trusty
sudo: false

os:
  - linux
  - osx

rust:
  - stable

before_install:
  - curl https://stainless-steel.github.io/travis/fortran.sh | bash

script:
  - cargo build -vv
  - cargo test -vv

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
