language: rust

os:
  - linux
  - osx

rust:
  - stable

before_install:
  - curl https://blas-lapack-rs.github.io/travis/fortran.sh | bash

script:
  - cargo test -vv

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
