language: rust

matrix:
  include:
    - os: linux
    - os: osx
      env: CC=gcc-9 FC=gfortran-9 LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/9

rust:
  - stable

before_install:
  - gfortran --version

script:
  - cargo test -vv

addons:
  apt:
    packages:
      - gfortran
  homebrew:
    packages:
      - gcc@9

notifications:
  email: false
