[package]

name = "netlib-blas-provider"
version = "0.0.3"
authors = ["Corey Richardson <corey@octayn.net>"]
links = "blas"
build = "build.rs"
repository = "https://github.com/cmr/netlib-blas-provider"
license = "BSL-1.0"
description = "BLAS/LAPACK provider using the Netlib implementation"

[lib]
name = "netlib-blas-provider"
path = "lib.rs"

[dependencies]
libc = "*"
