[package]
name = "netlib-provider"
version = "0.1.0"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
links = "blas"
build = "build.rs"
repository = "https://github.com/cmr/netlib-provider"
license = "BSL-1.0"
description = "BLAS/LAPACK provider using the Netlib implementation"

[lib]
name = "netlib_provider"
path = "lib.rs"

[features]
system-netlib = []
blas-only = []

[dependencies]
libc = "*"
