[package]

name = "netlib-blas-provider"
version = "0.0.1"
authors = ["Corey Richardson <corey@octayn.net>"]
links = "blas"
build = "build.rs"
repository = "https://github.com/cmr/openblas-blas-provider"
license = "BSL-1.0"
description = "BLAS provider using the excellent OpenBLAS implementation"

[lib]
name = "openblas-blas-provider"
path = "lib.rs"

[dependencies]
libc = "*"
