[package]
name = "netlib-provider"
version = "0.1.1"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
links = "blas"
build = "build.rs"
repository = "https://github.com/cmr/netlib-provider"
license = "BSL-1.0"
description = "BLAS/LAPACK provider using the Netlib implementation"
exclude = ["lapack/TESTING/*", "lapack/BLAS/TESTING/*", "lapack/CBLAS/testing/*"]

[lib]
name = "netlib_provider"
path = "lib.rs"

[features]
system-netlib = []
exclude-cblas = []
exclude-lapacke = []
