[package]
name = "netlib-provider"
version = "0.3.0"
license = "Apache-2.0/MIT"
authors = [
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides BLAS and LAPACK using the Netlib implementation."
homepage = "https://github.com/cmr/netlib-provider"
repository = "https://github.com/cmr/netlib-provider"
links = "blas"
build = "build.rs"
exclude = [
  "source/TESTING/*",
  "source/BLAS/TESTING/*",
  "source/CBLAS/testing/*",
]

[features]
default = ["include-cblas", "include-lapacke"]

include-cblas = []
include-lapacke = []
static-netlib = []
system-netlib = []

[build-dependencies]
cmake = "0.1"
