[package]
name = "netlib-blas-provider"
version = "0.0.5"
authors = ["Corey Richardson <corey@octayn.net>"]
links = "blas"
build = "build.rs"
repository = "https://github.com/cmr/netlib-blas-provider"
license = "BSL-1.0"
description = "BLAS/LAPACK provider using the Netlib implementation"

[lib]
name = "netlib_blas_provider"
path = "lib.rs"

[features]
system-netlib = []
blas-only = []

[dependencies]
libc = "*"
